---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: myapp
  namespace: default
  labels:
    environment: sandbox
    application: myapp
#  annotations:
#    fluxcd.io/automated: true
#    fluxcd.io/tag.chart-image: glob:sandbox-*
#    fluxcd.io/locked: true
spec:
  releaseName: myapp
  chart:
    git: 'git@github.com:michaelprice232/flux-config-repo.git'
    ref: master
    path: charts/myapp
  values:
    image:
      repository: 166475535369.dkr.ecr.eu-west-2.amazonaws.com/flux-demo-app1
      tag: sandbox-755b2f4cd8d0d00bdc0b92b49066f8c735b6e881
    ingress:
      enabled: true
      annotations: {kubernetes.io/ingress.class: nginx}
      hosts:
      - host: "a4d240a1916a211eab2540aa543139d2-400178828.eu-west-2.elb.amazonaws.com"
        paths: ["/"]
    replicaCount: 1
